# Generated by Django 4.0.4 on 2022-05-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('s_price', models.IntegerField()),
                ('m_price', models.IntegerField()),
                ('l_price', models.IntegerField()),
                ('items', models.CharField(choices=[('P', 'Pizza'), ('B', 'Burger'), ('R', 'Rice'), ('D', 'Dessert'), ('C', 'Coffee')], max_length=100)),
            ],
        ),
    ]
